package it.polimi.ingsw.model;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Random;

/**
 * This class is the container of the Action Tokens.
 */
public class TokenBag {
    private List<ActionToken> availableTokens;
    private List<ActionToken> usedTokens = new ArrayList<>();

    /**
     * Class constructor.
     * @param availableTokens An ArrayList containing the ActionToken generated by the game.
     */
    public TokenBag(ArrayList<ActionToken> availableTokens) {
        this.availableTokens = availableTokens;
        Collections.shuffle(availableTokens);
    }

    public List<ActionToken> getAvailableTokens() {
        return availableTokens;
    }

    public List<ActionToken> getUsedTokens() {
        return usedTokens;
    }

    /**
     * This method pick a random Action Token from the Token Bag.
     * @return The drawn Action Token.
     */
    public ActionToken drawToken() {
        Random random = new Random();
        int tokenIndex = random.nextInt(availableTokens.size());
        ActionToken extractedToken = availableTokens.get(tokenIndex);
        usedTokens.add(extractedToken);
        availableTokens.remove(tokenIndex);
        return extractedToken;
    }

    /**
     * This method fills the availableTokens list with the element of the usedTokens list, setting the Token Bag to its original state.
     */
    public void shuffle() {
        availableTokens.addAll(usedTokens);
        usedTokens.clear();
        Collections.shuffle(availableTokens);
    }

}
